name: "Heimdall"
description: >-
  "Applications Dashboard"
version: "2.6.1-ls265"
url: "https://github.com/EynErgy/HA_Add-Ons/tree/master/heimdall#readme"
slug: "heimdall"
init: false
startup: services
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: "Web Interface"
  443/tcp: "Web Interface SSL"
map:
  - ssl
  - addon_config:rw
  - share:rw
options:
  PUID: 1001
  PGID: 1001
schema:
  PUID: int
  PGID: int
  TZ: str?
image: eynergy/heimdall-{arch}
