---
name: Prometheus
version: "3.2.1"
slug: prometheus
description: Cloud native metrics
url: "https://github.com/EynErgy/HA_Add-Ons/tree/master/prometheus#readme"
startup: services
ingress: true
ingress_port: 9090
ingress_entry: graph
init: false
panel_icon: mdi:chart-timeline
panel_title: Prometheus
arch:
  - amd64
  - aarch64
hassio_api: true
homeassistant_api: true
map:
  - share:rw
ports:
  9090/tcp: null
ports_description:
  9090/tcp: Not required for Ingress
image: eynergy/prometheus-{arch}