name: "Heimdall"
description: >-
  "Applications Dashboard"
version: "2.6.1-ls258"
url: "https://github.com/EynErgy/HA_Add-Ons/tree/master/heimdall-vanilla#readme"
slug: "heimdall"
init: false
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: "Web interface"
  443/tcp: "Web interface SSL"
map:
  - ssl
  - addon_config:rw
  - share:rw
image: eynergy/ha_addons:{arch}-v2.6.1-ls258